GET http://localhost:8080/counterpart/goodname?name=apple
Accept: application/json

###
GET http://localhost:8080/goodcard/apple
Accept: application/json

###
GET http://localhost:8080/good/all

###
GET http://localhost:8080/good/item?name=apple
Accept: application/json

###
GET http://localhost:8080/good/category?category=fruit
Accept: application/json

###
GET http://localhost:8080/good/available/quantity?item=apple&date=2024/07/02
Accept: application/json

###
GET http://localhost:8080/good/salesincome/filter?conterpartName=Smirnov
Accept: application/json

###
GET http://localhost:8080/goodoperation/all
Accept: application/json

###GET http://localhost:8080/rating/get?goodName=apple&counterpartName=Smirnov
Accept: application/json

###
GET http://localhost:8080/rating/get/name?goodName=apple
Accept: application/json

###
GET http://localhost:1212/goodoperation/period?fromDate=2023/10/25&toDate=2023/10/30
Accept: application/json

###
GET http://localhost:1185/goodoperation/all
Accept: application/json

###
GET http://localhost:1176/good/salesincome/counterpart/good/period?counterpartName=supplier111&item=good1&dateFrom=2023/10/29&dateTo=2023/10/18
Accept: application/json

###
GET http://localhost:1176/good/salesincome/good/period?item=good1&dateFrom=2023/10/18&dateTo=2023/10/18
Accept: application/json

###
GET http://localhost:1175/good/salesincome/period?dateFrom=2023/10/18&dateTo=2023/10/18
Accept: application/json

###
GET http://localhost:1195/good/available/quantity?item=good1&date=2023/10/18
Accept: application/json

###
GET http://localhost:1183/good/counterpart?counterpartName=supplier8
Accept: application/json

###
GET http://localhost:1182/good/all
Accept: application/json

###
GET http://localhost:1201/goodcard/apple
Accept: application/json

###
GET http://localhost:1189/counterpart/goodname?name=good1
Accept: application/json

###
